version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    network_mode: host
    restart: unless-stopped
