
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Device Tracker
device_tracker:
  - platform: ddwrt
    host: ROUTER_IP_ADDRESS
    username: YOUR_ADMIN_USERNAME
    password: YOUR_ADMIN_PASSWORD

# Sensors
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: memory_use_percent
      - type: swap_use_percent
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: processor_use
      - type: processor_temperature

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
